# This GitHub workflow validates Bundle config (ML resource config and more)
# defined under my_mlops_project/resources/*
# and my_mlops_project/databricks.yml, when PRs are merged into the main branch
name: Bundle validation for my_mlops_project

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**'

env:
  DATABRICKS_HOST: https://adb-45915588051321.1.azuredatabricks.net
  DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
  DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
  

jobs:
  staging:
    concurrency: my_mlops_project-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - uses: databricks/setup-cli@main
        with:
          version: 0.297.2
      - name: Validate Bundle For Staging
        id: validate
        env:
          DATABRICKS_HOST: ${{ env.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ env.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ env.DATABRICKS_CLIENT_SECRET }}
          
        run: |
          databricks bundle validate -t staging > validate_output.txt
      - name: Create Comment with Bundle Configuration
        uses: actions/github-script@v7
        id: comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const fileContents = fs.readFileSync('validate_output.txt', 'utf8');
            const output = `#### Bundle Staging Config Validated 🖌
            <details><summary>Staging Validation Output</summary>

            \`\`\`\n
            ${fileContents}
            \`\`\`

            </details>`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

  